import React, { createContext, useContext, useState } from "react";

const LangCtx = createContext(null);

const dict = {
  en: {
    // landing
    tagline: "Learning, engineered by AI",
    hero_title_1: "Personalised tutoring",
    hero_title_2: "for every learner.",
    hero_sub:
      "MYTAMAN AI TUTOR blends pre-built KSSM curriculum with adaptive AI that generates summaries, quizzes, flashcards and mind maps — in English and Bahasa Melayu.",
    get_started: "Get started",
    login_admin: "Admin login",
    login_parent: "Parent login",
    login_student: "Learner login",
    about: "About",
    contact: "Contact",
    features: "Features",
    features_title: "Everything a modern classroom needs",
    features_sub: "One platform. Three seats. Zero fluff.",
    f1_title: "AI Content Studio",
    f1_body: "Upload a chapter — get summaries, quizzes, mind maps in seconds.",
    f2_title: "Model Router",
    f2_body: "Swap between OpenAI, Anthropic and Gemini with automatic failover.",
    f3_title: "Bilingual by design",
    f3_body: "Every artifact ships in English and Bahasa Melayu.",
    f4_title: "Progress tracking",
    f4_body: "Parents monitor, students learn, admins measure token cost.",
    about_title: "About MYTAMAN",
    about_body:
      "MYTAMAN is building the operating system for Malaysian secondary education. Our AI Tutor turns curriculum PDFs into interactive learning packs used by students and reviewed by educators.",
    contact_title: "Contact us",
    contact_body: "Reach the team for partnerships, school pilots, or enterprise licensing.",
    email: "Email",
    footer: "© MYTAMAN AI TUTOR. Built with adaptive AI.",
    // auth
    email_ph: "you@school.edu",
    password: "Password",
    name: "Full name",
    role: "Role",
    sign_in: "Sign in",
    sign_up: "Create account",
    no_account: "New here?",
    have_account: "Already have an account?",
    // dashboard shared
    overview: "Overview",
    generate: "Generate with AI",
    manual: "Manual content",
    router: "Model Router",
    packs: "Tutor Packs",
    students_label: "Students",
    logout: "Sign out",
    total_content: "Total content",
    published: "Published",
    // content gen
    pack: "Tutor Pack",
    title_label: "Title",
    content_type: "Content type",
    source_material: "Source material",
    generate_btn: "Generate with AI",
    generating: "Generating...",
    save_manual: "Save content",
    publish: "Publish",
    provider: "Provider",
    // router
    router_title: "Model Router settings",
    router_sub: "Add API keys, reorder failover, enable/disable providers, edit prompts.",
    api_key: "API key",
    save: "Save",
    remove: "Remove",
    enabled: "Enabled",
    disabled: "Disabled",
    system_prompts: "System prompts",
    // student
    my_packs: "My Tutor Packs",
    browse_packs: "Browse packs",
    dashboard: "Dashboard",
    enroll: "Enroll",
    enrolled: "Enrolled",
    // socratic
    socratic: "Socratic Learning",
    socratic_tutor: "Socratic Tutor",
    socratic_admin_title: "Socratic Learning",
    socratic_admin_sub:
      "The per-lesson AI tutor that guides students to answers instead of giving them. Available on Premium Tutor Packs. Every conversation is recorded and readable here.",
    premium_label: "Premium",
    socratic_hi: "Hi,",
    socratic_how_help: "How can I help?",
    socratic_placeholder: "Ask about this lesson",
    socratic_thinking: "Thinking…",
    socratic_new_chat: "New chat",
    socratic_hide: "Hide tutor",
    socratic_stuck: "I'm stuck",
    socratic_stuck_msg: "I'm stuck — can you give me a hint?",
    socratic_mastered: "You've worked this one out. Nice.",
    socratic_daily_limit: "You've reached today's tutor message limit. Come back tomorrow.",
    socratic_turn_limit: "This conversation has reached its limit. Start a new chat to keep going.",
    socratic_disclaimer:
      "This tutor is AI — it can make mistakes, so check anything important. It only discusses this lesson, and your parent and teacher can read these conversations. Don't share personal details.",
  },
  bm: {
    tagline: "Pembelajaran dijayakan AI",
    hero_title_1: "Tutor peribadi",
    hero_title_2: "untuk setiap pelajar.",
    hero_sub:
      "MYTAMAN AI TUTOR menggabungkan kurikulum KSSM sedia ada dengan AI adaptif — menjana ringkasan, kuiz, kad imbas dan peta minda dalam Bahasa Melayu dan Inggeris.",
    get_started: "Mula sekarang",
    login_admin: "Log masuk Admin",
    login_parent: "Log masuk Ibu Bapa",
    login_student: "Log masuk Pelajar",
    about: "Tentang",
    contact: "Hubungi",
    features: "Ciri-ciri",
    features_title: "Semua yang diperlukan bilik darjah moden",
    features_sub: "Satu platform. Tiga peranan. Tanpa gimik.",
    f1_title: "Studio Kandungan AI",
    f1_body: "Muat naik bab — dapat ringkasan, kuiz, peta minda dalam saat.",
    f2_title: "Penghala Model",
    f2_body: "Bertukar antara OpenAI, Anthropic dan Gemini secara automatik.",
    f3_title: "Dwibahasa secara asli",
    f3_body: "Setiap artifak tersedia dalam BM dan Inggeris.",
    f4_title: "Pantauan progres",
    f4_body: "Ibu bapa memantau, pelajar belajar, admin mengukur kos token.",
    about_title: "Tentang MYTAMAN",
    about_body:
      "MYTAMAN membina sistem operasi untuk pendidikan menengah Malaysia. AI Tutor kami menukar PDF kurikulum kepada pek pembelajaran interaktif.",
    contact_title: "Hubungi kami",
    contact_body: "Hubungi kami untuk kerjasama, uji-jalan sekolah, atau lesen enterprise.",
    email: "Emel",
    footer: "© MYTAMAN AI TUTOR. Dibina dengan AI adaptif.",
    email_ph: "anda@sekolah.edu",
    password: "Kata laluan",
    name: "Nama penuh",
    role: "Peranan",
    sign_in: "Log masuk",
    sign_up: "Daftar akaun",
    no_account: "Baru di sini?",
    have_account: "Sudah ada akaun?",
    overview: "Gambaran keseluruhan",
    generate: "Jana dengan AI",
    manual: "Kandungan manual",
    router: "Penghala Model",
    packs: "Pek Tutor",
    students_label: "Pelajar",
    logout: "Log keluar",
    total_content: "Jumlah kandungan",
    published: "Diterbitkan",
    pack: "Pek Tutor",
    title_label: "Tajuk",
    content_type: "Jenis kandungan",
    source_material: "Bahan sumber",
    generate_btn: "Jana dengan AI",
    generating: "Menjana...",
    save_manual: "Simpan kandungan",
    publish: "Terbitkan",
    provider: "Pembekal",
    router_title: "Tetapan Penghala Model",
    router_sub: "Tambah kunci API, susun failover, aktif/nyahaktif pembekal, edit prompt.",
    api_key: "Kunci API",
    save: "Simpan",
    remove: "Buang",
    enabled: "Aktif",
    disabled: "Nyahaktif",
    system_prompts: "Prompt sistem",
    my_packs: "Pek Tutor Saya",
    browse_packs: "Semak imbas pek",
    dashboard: "Papan Pemuka",
    enroll: "Daftar",
    enrolled: "Didaftarkan",
    socratic: "Pembelajaran Socratic",
    socratic_tutor: "Tutor Socratic",
    socratic_admin_title: "Pembelajaran Socratic",
    socratic_admin_sub:
      "Tutor AI setiap pelajaran yang membimbing pelajar mencari jawapan sendiri, bukan memberi jawapan. Tersedia untuk Pek Tutor Premium. Setiap perbualan direkod dan boleh dibaca di sini.",
    premium_label: "Premium",
    socratic_hi: "Hai,",
    socratic_how_help: "Apa yang boleh saya bantu?",
    socratic_placeholder: "Tanya tentang pelajaran ini",
    socratic_thinking: "Sedang berfikir…",
    socratic_new_chat: "Perbualan baharu",
    socratic_hide: "Sembunyikan tutor",
    socratic_stuck: "Saya buntu",
    socratic_stuck_msg: "Saya buntu — boleh beri saya petunjuk?",
    socratic_mastered: "Anda berjaya menyelesaikannya. Syabas.",
    socratic_daily_limit: "Anda telah mencapai had mesej tutor hari ini. Kembali esok.",
    socratic_turn_limit: "Perbualan ini telah mencapai hadnya. Mulakan perbualan baharu untuk teruskan.",
    socratic_disclaimer:
      "Tutor ini ialah AI — ia boleh melakukan kesilapan, jadi semak perkara penting. Ia hanya membincangkan pelajaran ini, dan ibu bapa serta guru anda boleh membaca perbualan ini. Jangan kongsi maklumat peribadi.",
  },
};

export const LangProvider = ({ children }) => {
  const [lang, setLang] = useState(localStorage.getItem("mytaman_lang") || "en");
  const setL = (l) => {
    localStorage.setItem("mytaman_lang", l);
    setLang(l);
  };
  const t = (key) => dict[lang][key] ?? key;
  return <LangCtx.Provider value={{ lang, setLang: setL, t }}>{children}</LangCtx.Provider>;
};

export const useLang = () => useContext(LangCtx);
