import React, { createContext, useContext, useState } from "react";

const LangCtx = createContext(null);

const dict = {
  en: {
    // landing
    tagline: "Learning, engineered by AI",
    hero_title_1: "Personalised tutoring",
    hero_title_2: "for every learner.",
    hero_sub:
      "Turn a KSSM chapter into notes, a mind map, a summary, flashcards and a quiz — in Bahasa Melayu and English, ready in minutes instead of a weekend.",
    get_started: "Get started",
    login_admin: "Admin login",
    login_parent: "Parent login",
    login_student: "Learner login",
    about: "About",
    contact: "Contact",
    features: "Features",
    features_title: "Built for every seat in the school",
    features_sub: "Students, parents and educators — one platform, three very different jobs.",
    f1_title: "For students",
    f1_body: "Revise the way that suits you — read it, map it, drill it, or test yourself — and keep the habit going with XP and streaks.",
    f2_title: "For parents",
    f2_body: "See what your child studied, how long they spent and where they got stuck, without reading over their shoulder.",
    f3_title: "For educators",
    f3_body: "Generate a term of material from chapters you already teach, review every draft, and publish only what you're happy with.",
    f4_title: "For whoever pays the bill",
    f4_body: "Watch requests, latency and token spend per model from one dashboard, and cap usage before a spike becomes an invoice.",
    about_title: "About Lv99.ai",
    about_body:
      "Lv99.ai turns the KSSM chapters schools already teach into interactive learning packs — generated by AI, reviewed by educators before anyone sees them, and studied in whichever language a learner thinks in.",
    contact_title: "Contact us",
    contact_body: "Talk to us about school pilots, partnerships or licensing — a real person reads every message.",
    email: "Email",
    footer: "© Lv99.ai. Built with adaptive AI.",

    // --- Landing: stats, pipeline, progression, asset slot ---
    stat_types: "content types generated per chapter",
    stat_langs: "languages, generated side by side",
    stat_providers: "AI providers with automatic failover",
    stat_levels: "levels to climb, from Lv1 to Lv99",

    under_hood: "Under the hood",
    under_hood_title_1: "Engineered for how students",
    under_hood_title_2: "actually learn",
    under_hood_sub:
      "Not a chatbot bolted onto a textbook. Every layer is built around one chapter at a time, in the language the student thinks in.",
    uh1_title: "Multi-provider Model Router",
    uh1_body:
      "OpenAI, Anthropic and Gemini behind one router, with automatic failover and per-provider rate limits — so a lesson still generates when a provider is slow or down.",
    uh2_title: "Bilingual by construction",
    uh2_body:
      "Every lesson is produced in Bahasa Melayu and English and aligned line for line, so a student can read either language — or both at once — without losing their place.",
    uh3_title: "A tutor that asks before it answers",
    uh3_body:
      "The Socratic tutor leads with questions and escalates hints only as far as a student actually needs, so understanding is earned rather than handed over.",
    uh4_title: "Grounded in your curriculum",
    uh4_body:
      "Every lesson is built from the chapter material you upload, never scraped from the open web — so nothing reaches a student that you didn't put in.",

    progression: "Progression",
    progression_title: "Learning, leveled up.",
    progression_body:
      "Every lesson earns XP and every day you return compounds your streak. Missions, mystery chests and a season pass turn revision into a run worth finishing — all the way to Lv99.",
    g_xp: "XP for every lesson & quiz",
    g_streak: "Daily streaks that compound",
    g_missions: "Weekly missions & challenges",
    g_season: "Season pass rewards",
    g_level: "Level",
    g_xp_earned: "XP earned",
    g_chest: "Mystery chest",
    g_spin: "Lucky spin",
    g_badge: "Achievements",

    mascot_title: "Your AI study companion, arriving soon",
    mascot_body:
      "This space is reserved for the Lv99 companion — an animated 3D character that reacts as you learn. The layout, lighting and motion are already in place, waiting on the artwork.",
    // auth
    email_ph: "you@school.edu",
    password: "Password",
    name: "Full name",
    role: "Role",
    sign_in: "Sign in",
    sign_up: "Create account",
    no_account: "New here?",
    have_account: "Already have an account?",
    // dashboard shared
    overview: "Overview",
    generate: "Generate with AI",
    manual: "Manual content",
    router: "Model Router",
    packs: "Tutor Packs",
    students_label: "Students",
    logout: "Sign out",
    total_content: "Total content",
    published: "Published",
    // content gen
    pack: "Tutor Pack",
    title_label: "Title",
    content_type: "Content type",
    source_material: "Source material",
    generate_btn: "Generate with AI",
    generating: "Generating...",
    save_manual: "Save content",
    publish: "Publish",
    provider: "Provider",
    // router
    router_title: "Model Router settings",
    router_sub: "Add API keys, reorder failover, enable/disable providers, edit prompts.",
    api_key: "API key",
    save: "Save",
    remove: "Remove",
    enabled: "Enabled",
    disabled: "Disabled",
    system_prompts: "System prompts",
    // student
    my_packs: "My Tutor Packs",
    browse_packs: "Browse packs",
    dashboard: "Dashboard",
    enroll: "Enroll",
    enrolled: "Enrolled",
    switch_pack: "Switch to this pack",
    current_pack: "Current",
    one_pack_rule: "You can study one Tutor Pack at a time — enrolling in a new one replaces your current pack.",
    one_pack_current: "You're currently on",
    // socratic
    socratic: "Socratic Learning",
    accounts: "Account Manager",
    socratic_tutor: "Socratic Tutor",
    socratic_tutor_suffix: "Tutor",
    socratic_intro:
      "Hello! I'm {name}, your friendly AI tutor. I'm here to help you work through {lesson}. I won't just hand you answers — I'll ask questions until you get there yourself. What shall we start with?",
    socratic_this_lesson: "this lesson",
    socratic_collapse: "Click to collapse",
    socratic_admin_title: "Socratic Learning",
    socratic_admin_sub:
      "The per-lesson AI tutor that guides students to answers instead of giving them. Available on every Tutor Pack a student is enrolled in. Every conversation is recorded and readable here.",
    premium_label: "Tutor",
    socratic_hi: "Hi,",
    socratic_how_help: "How can I help?",
    socratic_placeholder: "Ask about this lesson",
    socratic_thinking: "Thinking…",
    socratic_new_chat: "New chat",
    socratic_hide: "Hide tutor",
    socratic_stuck: "I'm stuck",
    socratic_stuck_msg: "I'm stuck — can you give me a hint?",
    socratic_hints_spent: "You've used all your hints for this lesson — keep working it through with the tutor.",
    socratic_mastered: "You've worked this one out. Nice.",
    socratic_daily_limit: "You've reached today's tutor message limit. Come back tomorrow.",
    socratic_turn_limit: "This conversation has reached its limit. Start a new chat to keep going.",
    socratic_disclaimer:
      "This tutor is AI — it can make mistakes, so check anything important. It only discusses this lesson, and your parent and teacher can read these conversations. Don't share personal details.",
  },
  bm: {
    tagline: "Pembelajaran dijayakan AI",
    hero_title_1: "Tutor peribadi",
    hero_title_2: "untuk setiap pelajar.",
    hero_sub:
      "Tukar satu bab KSSM kepada nota, peta minda, ringkasan, kad imbas dan kuiz — dalam Bahasa Melayu dan Inggeris, siap dalam beberapa minit, bukan hujung minggu.",
    get_started: "Mula sekarang",
    login_admin: "Log masuk Admin",
    login_parent: "Log masuk Ibu Bapa",
    login_student: "Log masuk Pelajar",
    about: "Tentang",
    contact: "Hubungi",
    features: "Ciri-ciri",
    features_title: "Dibina untuk setiap peranan di sekolah",
    features_sub: "Pelajar, ibu bapa dan pendidik — satu platform, tiga tugas yang berbeza.",
    f1_title: "Untuk pelajar",
    f1_body: "Ulang kaji ikut cara anda — baca, petakan, latih tubi atau uji diri — dan kekalkan tabiat itu dengan XP dan rentetan harian.",
    f2_title: "Untuk ibu bapa",
    f2_body: "Lihat apa yang dipelajari anak anda, berapa lama, dan di mana mereka tersekat — tanpa perlu menjenguk dari belakang.",
    f3_title: "Untuk pendidik",
    f3_body: "Jana bahan satu penggal daripada bab yang anda sudah ajar, semak setiap draf, dan terbitkan hanya apa yang anda puas hati.",
    f4_title: "Untuk yang menanggung kos",
    f4_body: "Pantau permintaan, latensi dan perbelanjaan token bagi setiap model dari satu papan pemuka, dan hadkan penggunaan sebelum lonjakan menjadi bil.",
    about_title: "Tentang Lv99.ai",
    about_body:
      "Lv99.ai menukar bab KSSM yang sudah diajar di sekolah kepada pek pembelajaran interaktif — dijana oleh AI, disemak pendidik sebelum sampai kepada sesiapa, dan dipelajari dalam bahasa yang difikirkan pelajar.",
    contact_title: "Hubungi kami",
    contact_body: "Hubungi kami untuk uji-jalan sekolah, kerjasama atau pelesenan — setiap mesej dibaca oleh manusia sebenar.",
    email: "Emel",
    footer: "© Lv99.ai. Dibina dengan AI adaptif.",

    // --- Landing: stats, pipeline, progression, asset slot ---
    stat_types: "jenis kandungan dijana bagi setiap bab",
    stat_langs: "bahasa, dijana seiring",
    stat_providers: "penyedia AI dengan failover automatik",
    stat_levels: "tahap untuk didaki, dari Lv1 ke Lv99",

    under_hood: "Di sebalik tabir",
    under_hood_title_1: "Direka untuk cara pelajar",
    under_hood_title_2: "benar-benar belajar",
    under_hood_sub:
      "Bukan sekadar chatbot yang dicantum pada buku teks. Setiap lapisan dibina mengelilingi satu bab pada satu masa, dalam bahasa yang difikirkan pelajar.",
    uh1_title: "Model Router pelbagai penyedia",
    uh1_body:
      "OpenAI, Anthropic dan Gemini di sebalik satu router, dengan failover automatik dan had kadar bagi setiap penyedia — jadi pelajaran tetap dijana walaupun satu penyedia perlahan atau tergendala.",
    uh2_title: "Dwibahasa secara reka bentuk",
    uh2_body:
      "Setiap pelajaran dihasilkan dalam Bahasa Melayu dan Inggeris serta diselaraskan baris demi baris, supaya pelajar boleh membaca mana-mana bahasa — atau kedua-duanya sekali.",
    uh3_title: "Tutor yang bertanya sebelum menjawab",
    uh3_body:
      "Tutor Socratic memimpin dengan soalan dan menaikkan bantuan hanya sejauh yang diperlukan pelajar, supaya kefahaman diperoleh sendiri dan bukan sekadar diberi.",
    uh4_title: "Berteraskan kurikulum anda",
    uh4_body:
      "Setiap pelajaran dibina daripada bahan bab yang anda muat naik, bukan diambil dari internet terbuka — jadi tiada apa yang sampai kepada pelajar yang anda tidak masukkan.",

    progression: "Perkembangan",
    progression_title: "Pembelajaran, dinaik taraf.",
    progression_body:
      "Setiap pelajaran memberi XP dan setiap hari anda kembali menambah rentetan anda. Misi, peti misteri dan pas musim menjadikan ulang kaji satu perjalanan yang berbaloi dihabiskan — sehingga ke Lv99.",
    g_xp: "XP bagi setiap pelajaran & kuiz",
    g_streak: "Rentetan harian yang terkumpul",
    g_missions: "Misi & cabaran mingguan",
    g_season: "Ganjaran pas musim",
    g_level: "Tahap",
    g_xp_earned: "XP diperoleh",
    g_chest: "Peti misteri",
    g_spin: "Putaran bertuah",
    g_badge: "Pencapaian",

    mascot_title: "Rakan belajar AI anda, akan tiba tidak lama lagi",
    mascot_body:
      "Ruang ini dikhaskan untuk rakan Lv99 — watak 3D beranimasi yang bertindak balas semasa anda belajar. Susun atur, pencahayaan dan pergerakan sudah sedia, menunggu karya seninya.",
    email_ph: "anda@sekolah.edu",
    password: "Kata laluan",
    name: "Nama penuh",
    role: "Peranan",
    sign_in: "Log masuk",
    sign_up: "Daftar akaun",
    no_account: "Baru di sini?",
    have_account: "Sudah ada akaun?",
    overview: "Gambaran keseluruhan",
    generate: "Jana dengan AI",
    manual: "Kandungan manual",
    router: "Penghala Model",
    packs: "Pek Tutor",
    students_label: "Pelajar",
    logout: "Log keluar",
    total_content: "Jumlah kandungan",
    published: "Diterbitkan",
    pack: "Pek Tutor",
    title_label: "Tajuk",
    content_type: "Jenis kandungan",
    source_material: "Bahan sumber",
    generate_btn: "Jana dengan AI",
    generating: "Menjana...",
    save_manual: "Simpan kandungan",
    publish: "Terbitkan",
    provider: "Pembekal",
    router_title: "Tetapan Penghala Model",
    router_sub: "Tambah kunci API, susun failover, aktif/nyahaktif pembekal, edit prompt.",
    api_key: "Kunci API",
    save: "Simpan",
    remove: "Buang",
    enabled: "Aktif",
    disabled: "Nyahaktif",
    system_prompts: "Prompt sistem",
    my_packs: "Pek Tutor Saya",
    browse_packs: "Semak imbas pek",
    dashboard: "Papan Pemuka",
    enroll: "Daftar",
    enrolled: "Didaftarkan",
    switch_pack: "Tukar ke pek ini",
    current_pack: "Semasa",
    one_pack_rule: "Anda boleh belajar satu Pek Tutor pada satu masa — mendaftar pek baharu akan menggantikan pek semasa anda.",
    one_pack_current: "Anda kini menggunakan",
    socratic: "Pembelajaran Socratic",
    accounts: "Pengurus Akaun",
    socratic_tutor: "Tutor Socratic",
    socratic_tutor_suffix: "Tutor",
    socratic_intro:
      "Hai! Saya {name}, tutor AI mesra anda. Saya di sini untuk membantu anda memahami {lesson}. Saya tidak akan terus memberi jawapan — saya akan bertanya sehingga anda menemuinya sendiri. Apa yang hendak kita mulakan?",
    socratic_this_lesson: "pelajaran ini",
    socratic_collapse: "Klik untuk lipat",
    socratic_admin_title: "Pembelajaran Socratic",
    socratic_admin_sub:
      "Tutor AI setiap pelajaran yang membimbing pelajar mencari jawapan sendiri, bukan memberi jawapan. Tersedia untuk setiap Pek Tutor yang didaftari pelajar. Setiap perbualan direkod dan boleh dibaca di sini.",
    premium_label: "Tutor",
    socratic_hi: "Hai,",
    socratic_how_help: "Apa yang boleh saya bantu?",
    socratic_placeholder: "Tanya tentang pelajaran ini",
    socratic_thinking: "Sedang berfikir…",
    socratic_new_chat: "Perbualan baharu",
    socratic_hide: "Sembunyikan tutor",
    socratic_stuck: "Saya buntu",
    socratic_stuck_msg: "Saya buntu — boleh beri saya petunjuk?",
    socratic_hints_spent: "Anda telah menggunakan semua petunjuk untuk pelajaran ini — teruskan berbincang dengan tutor.",
    socratic_mastered: "Anda berjaya menyelesaikannya. Syabas.",
    socratic_daily_limit: "Anda telah mencapai had mesej tutor hari ini. Kembali esok.",
    socratic_turn_limit: "Perbualan ini telah mencapai hadnya. Mulakan perbualan baharu untuk teruskan.",
    socratic_disclaimer:
      "Tutor ini ialah AI — ia boleh melakukan kesilapan, jadi semak perkara penting. Ia hanya membincangkan pelajaran ini, dan ibu bapa serta guru anda boleh membaca perbualan ini. Jangan kongsi maklumat peribadi.",
  },
};

export const LangProvider = ({ children }) => {
  const [lang, setLang] = useState(localStorage.getItem("mytaman_lang") || "en");
  const setL = (l) => {
    localStorage.setItem("mytaman_lang", l);
    setLang(l);
  };
  const t = (key) => dict[lang][key] ?? key;
  return <LangCtx.Provider value={{ lang, setLang: setL, t }}>{children}</LangCtx.Provider>;
};

export const useLang = () => useContext(LangCtx);
